services:
  backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/usr/src/app

  cli:
    build:
      context: .
      dockerfile: ./_docker/cli/Dockerfile
    volumes:
      - .:/app
    tty: true
    ports:
      - "8000:8000"


networks:
  default:
    name: my_network