openapi: 3.0.1
info:
  title: Session-based API
  description: API specification for session management and chat functionalities.
  version: 1.0.0
servers:
  - url: http://localhost:8002
    description: Production server
paths:
  /register/:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - name
                - email
                - password
      responses:
        201:
          description: User registered successfully
          headers:
            Set-Cookie:
              description: Session ID cookie
              schema:
                type: string
        400:
          description: Bad request (e.g., email already registered)
  /login/:
    post:
      summary: Login and retrieve session ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  nullable: true
                email:
                  type: string
                  format: email
                  nullable: true
                password:
                  type: string
                  format: password
              required:
                - password
      responses:
        200:
          description: Login successful
          headers:
            Set-Cookie:
              description: Session ID cookie
              schema:
                type: string
        400:
          description: Bad request (e.g., both name and email are missing)
        401:
          description: Unauthorized (invalid credentials)
  /user/:
    get:
      summary: Get user information
      responses:
        200:
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  created_at:
                    type: string
                    format: date-time
        401:
          description: Unauthorized (invalid session)
    patch:
      summary: Update user information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          description: User information updated successfully
        401:
          description: Unauthorized (invalid session)
  /chat/:
    post:
      summary: Post a chat message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
      responses:
        200:
          description: Chat response from GPT
          content:
            application/json:
              schema:
                type: object
                properties:
                  gpt_response:
                    type: string
        401:
          description: Unauthorized (invalid session)
  /chat/history/:
    get:
      summary: Get chat history
      responses:
        200:
          description: Chat history retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
                    user_message:
                      type: string
                    gpt_response:
                      type: string
        401:
          description: Unauthorized (invalid session)
  /statistics/:
    get:
      summary: Get statistics
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
        401:
          description: Unauthorized (invalid session)
components:
  securitySchemes:
    SessionID:
      type: apiKey
      in: cookie
      name: sessionid
    CSRFToken:
      type: apiKey
      in: cookie
      name: csrftoken
security:
  - SessionID: []
  - CSRFToken: []
