name: CI

# trigger
on:
  push:
    branches: [ main, test ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.15.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd frontend && yarn install
    - run: cd frontend && yarn build
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: frontend/dist/

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Download build result
      uses: actions/download-artifact@v4
      with:
        name: build
        path: frontend/dist/
    - name: Publish to AWS S3
      uses: opspresso/action-s3-sync@v0.2.6
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        FROM_PATH: "frontend/dist/"
        DEST_PATH: "s3://emocare-bucket"
    - name: Clear cache in CloudFront
      uses: chetan/invalidate-cloudfront-action@v2.4
      env:
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        PATHS: "/*"
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}